### PR TITLE
Fix PE-D bugs for batch commands

### LINKED ISSUE #207: [PE-D][Tester D] Batch edit Command: Breaks if new details contain the word "to"
By using the parameter `/d` and including the word 'to' in its details would result in an error message being shown instead.

### Steps to reproduce:
1. Ensure there are two users with role as 'QA Engineer'
2. Type "batch edit r/QA Engineer to d/met to discuss"

### Expected Result:
details of two users are edited accordingly, storing "met to discuss" as its details
"Edited 2 person(s)" as expected output

### Actual Result:
Error message is shown, showing "Invalid command format" message
Image

```
Invalid command format! 
batch edit: Edits all persons whose attributes match the specified condition(s).
Parameters: [s/STATUS] [r/ROLE]... [rt/RATING_CONDITION] [dt/DATE_CONDITION] to [EDITS]
Example: batch edit s/APPLIED dt/before 2024-01-01 to s/REJECTED
```

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #208: [PE-D][Tester A] `batch delete` only deletes matches from current visible list, not the whole address book
### **Problem:**
`batch delete` is currently scoped to the visible list rather than the full address book.

According to the **user guide**(top image) and the **developer guide**(bottom image) it states that batch delete should delete all `persons` whose attributes matches the attributes.
Image

Image

### **The way the bug I found the bug is:**
- run `find Bernice`
- See that only Bernice is shown.

Image
 
- run `batch delete s/Offered`
- it shows "Deleted 1 person(s)"
- run `list` again
- There will still be people inside that have status "offered", so the `batch delete` did not work as intended. But Bernice is deleted as intended 👍 

Image

### **Suggestion:**
- I've made a similar mistake before so i think it's just that wrong list is being fetched here. E.g. fetching `model.FIlteredPersonList()` instead of the `model.PersonList()`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #211: [PE-D][Tester A] `batch edit` only deletes matches from current visible list, not the whole address book
### **Problem:**
`batch edit` is currently scoped to the visible list rather than the full address book.

According to the **user guide**(top image) and the **developer guide**(bottom image) it states that batch delete should delete all `persons` whose attributes matches the attributes.

Image

Image

### **The way the bug I found the bug is:**
- run `find Bernice`
- See that only Bernice is shown.
Image
 
- run `batch edit s/Offered to s/Rejected`
- it shows "Edited 1 person(s)"
- run `list` again
- There will still be people inside that have status "offered", so the `batch edit` did not work as intended. But Bernice is edited to `Rejected` status as intended 👍 
Image

### **Suggestion:**
- I've made a similar mistake before so i think it's just that wrong list is being fetched here. E.g. fetching `model.FIlteredPersonList()` instead of the `model.PersonList()`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #216: [PE-D][Tester A] Failed `batch edit` is non-atomic and can leave partial edits
### **Problem:**
A failed `batch edit` should not leave the address book half-updated. Currently, one person can be edited successfully, then a later duplicate clash aborts the command, resulting in the data being partially modified.

The DG (3a), says that a duplicate conflict should be reported as an error instead of modifying them.

Image

### **Steps i took to get the bug:**
- run `batch edit s/Offered to n/Alweezy p/99999`

**_Initial State_**
Image

**_After State_**
Image

**Actual behavior**
Step 1 (running the batch edit command) fails with Batch edit resulted in a duplicate person in the address book. Step 4 still shows one edited person (Charlotte becomes Alweezy with the new phone number), so the failed command has already changed the data.

**Expected behavior**
If the batch edit fails because it would create duplicates, no candidate should be edited.

### **Suggestions**
It might be possible that the code is editing the person before duplicate checks are done, maybe the order can be switched? This is either a documentation or funtionality bug, not too sure myself.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #218: [PE-D][Tester A] `batch edit` rejects valid edit values that contain the word-separator `to`
### **Problem**
The parser splits on every literal `to`, so a valid status such as Ready to Interview is rejected even though statuses are otherwise allowed to be arbitrary non-blank text.

### **Steps i took to produce bug:**
- run `batch edit s/Accepted to s/Ready to interview`
Image

**Actual behavior**
The command is rejected with invalid command format.

**Expected behavior**
The command should succeed and update all Accepted candidates to the valid status Ready to Interview.

### **Suggestions**
- The bug can definitely be solved by changing the parser code. It probably splits according to `to` right now. Maybe a different way of parser can be considered.
- Running the above steps while removing the `to` in `s/Ready to interview` allows the command to execute as expected, so I'm sure you're very close! Just need to tweak the parser logic slightly 👍 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #226: [PE-D][Tester D] Batch edit Command: Non-atomic and can leave partial updates after failing on duplicate
When batch edit includes both 'n/' and 'p/' parameters, and is used on multiple people, the first edit succeeds, while the later edits on the next person would create a duplicate person and fails without reverting the first edit.

### Steps to reproduce:
1. Ensure there are 2 users with role 'Software Engineer'
2. Type and execute `batch edit r/Software Engineer to n/John Doe p/12345678 e/john@example.com s/Accepted rs/Yes`

### Expected Result:
Command should not be executed. None of the users are updated.
### Actual Result:
Earlier edits remain applied, even though the command ultimately fails.
ID 1 is edited accordingly. However, ID 5 remains unchanged due to duplicate persons. Command executes partially.
Image

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #238: [PE-D][Tester D] batch edit/batch delete command only affects the currently filtered list
Commands only affect the currently filtered list, and not the whole address book, as stated in the User Guide.

Image

### Steps to reproduce:
1. Ensure there are 2 users with the name 'Alex' with status as 'Accepted' or 'Approved', and other users with 'Offered' as status
2. Type and execute `find alex`
3. Type and execute `batch delete s/Offered`

### Expected Result:
All users with 'Offered' as status should be deleted, regardless of whether it is being currently listed or not.
Commands should apply to all persons in the address book.

### Actual Result:
Error message shown with no persons matching the specified criteria.
Users that are not listed with 'Alex' in its name but with 'Offered' as status are not deleted. 
Hidden persons are skipped and not deleted.

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #239: [PE-D][Tester C] sort accepts more than 1 field if the prefixes are the same
In the UG, it is stated that:

> You can only sort by one field at a time.

However, `sort rt/asc rt/desc` does not throw any error and instead executes identical to `sort rt/desc`.

Image

This is potentially problematic behaviour as it is undocumented in the UG.

Steps to reproduce:
Pre-condition: Use the sample data provided by HireShell.
1. Execute `sort rt/asc rt/desc`.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #240: [PE-D][Tester D] batch delete command: User Guide omits dt/DATE_CONDITION even though command supports it
User Guide omits dt/DATE_CONDITION even though batch delete command supports it. It is also shown accordingly in its error message.

Image

### Steps to reproduce:
1. Read the batch delete command format in the User Guide
2. Note that [dt/DATE_CONDITION] is not included

Image

### Expected Result:
Under User Guide, batch delete format should include all supported parameters, including date condition.

### Actual Result:
batch delete format lists only [s/STATUS] [r/ROLE]... [rt/RATING_CONDITION].
Implementation includes date condition.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #244: [PE-D][Tester D] batch edit command: User Guide omits dt/DATE_CONDITION even though command supports it
User Guide omits dt/DATE_CONDITION even though batch edit command supports it. It is also shown accordingly in its error message.

Image

### Steps to reproduce:
1. Read the batch delete command format in the User Guide
2. Note that [dt/DATE_CONDITION] is not included

Image

### Expected Result:
Under User Guide, batch edit format should include all supported parameters, including date condition.
Format should include [dt/DATE_CONDITION] on the left side of to.

### Actual Result:
batch edit format lists only [s/STATUS] [r/ROLE]... [rt/RATING_CONDITION] on the left side of to.
Implementation includes date condition.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by SuhanKim96**
Fixes #240 
Fixes #244 
Fixes #238 
Fixes #226 
Fixes #218 
Fixes #216 
Fixes #211 
Fixes #239 
Fixes #208 
Fixes #207

### CODE REVIEW

File: src/main/java/seedu/hireshell/logic/commands/BatchEditCommand.java [hunk 1]
```diff
@@ -72,17 +72,20 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_NO_PERSONS_MATCHED);
         }
 
+        List<Person> editedPersons = new ArrayList<>();
         for (Person personToEdit : personsToEdit) {
             Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
-
```
Comment (NUSOffisher) [inline src/main/java/seedu/hireshell/logic/commands/BatchEditCommand.java:77]: I think we can add this empty line back to line 77 to conserve your LOC tracked during the feature freeze

**Review by nivanthn — APPROVED** [review]
LGTM

**Review by Ke1sT — APPROVED** [review]
LGTM
